#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
BRAIN="$ROOT/.repo-brain"
DIAG="$BRAIN/diagnosis.json"

log() { echo "🐙 [auto-pr] $1"; }

[ -f "$DIAG" ] || exit 0
status=$(${JQ_BIN:-jq} -r '.status' "$DIAG")

if [ "$status" != "AUTO_FIXABLE" ]; then
  log "Repo is $status. Skipping PR creation."
  exit 0
fi

BRANCH="brain/normalization-$(date +'%Y%m%d')"

log "Creating branch $BRANCH"
git checkout -b "$BRANCH" || git checkout "$BRANCH"

log "Staging MERMEDA infrastructure updates"
git add .github/workflows/ .repo-brain/ .gitignore
git commit -m "chore(brain): autonomous infrastructure normalization (MERMEDA v1.1.0)" || true

if [ -n "${GITHUB_TOKEN:-}" ]; then
  log "Pushing branch and creating Pull Request..."
  git push origin "$BRANCH"
  
  # Simulated PR creation via GitHub CLI (assuming installed in Action)
  if command -v gh >/dev/null 2>&1; then
    gh pr create \
      --title "🧠 [BRAIN] Infrastructure Normalization" \
      --body "This PR was autonomously generated by REPO BRAIN HOSPITAL to align this repository with the MERMEDA v1.1.0 governance spec." \
      --label "governance" \
      --label "automerge"
      
    log "PR Created and labeled for automerge."
  fi
else
  log "Dry-run: PR creation skipped (missing GITHUB_TOKEN)"
fi
