name: Python CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f pyproject.toml ]; then
            pip install . || true
          fi

      - name: Test
        run: |
          if command -v pytest >/dev/null 2>&1; then
            pytest
          elif [ -d tests ]; then
            python -m unittest discover
          else
            echo "No tests found"
          fi
