name: Solidity CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry test (if foundry.toml)
        if: hashFiles('foundry.toml') != ''
        run: forge test -vvv

      - name: Node setup (for Hardhat)
        if: hashFiles('hardhat.config.*') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (Hardhat)
        if: hashFiles('hardhat.config.*') != ''
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Hardhat test
        if: hashFiles('hardhat.config.*') != ''
        run: npx hardhat test
